namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class AtomicStep : ProcessStep
    {
#pragma warning disable IDE1006





#pragma warning restore IDE1006
    }

}
