namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class CollectionType : DataType
    {
#pragma warning disable IDE1006


        public DataType collectionItemType { get; set; }



#pragma warning restore IDE1006
    }

}
