
namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public enum Comparator
    {
        GreaterThan = 0,
        SmallerThan = 1,
        GreaterThanOrEqual = 2,
        SmallerThanOrEqual = 3,
        Equal = 4,
        Distinct = 5,
        Identic = 6
    }

}
