using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class ComplexType : DataType
    {
#pragma warning disable IDE1006


        public List<DataType> subtypes { get; set; }
        public List<DataType> subreferences { get; set; }



#pragma warning restore IDE1006
    }

}
