using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class CompositeStep : ProcessStep
    {
#pragma warning disable IDE1006


        public List<ProcessStep> subSteps { get; set; }



#pragma warning restore IDE1006
    }

}
