namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class Condition
    {
#pragma warning disable IDE1006
        public Comparator comparator { get; set; }


        public StartDataPort leftSide { get; set; }
        public StartDataPort rightSide { get; set; }



#pragma warning restore IDE1006
    }

}
