namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public interface CpsStep
    {
#pragma warning disable IDE1006
        bool cyberPhysical { get; set; }
        string goal { get; set; }
        string eplQuery { get; set; }
        string controlProcessId { get; set; }
        string context { get; set; }


        Process controlProcess { get; set; }



#pragma warning restore IDE1006
    }

}
