using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public abstract class DataPort : Port
    {
#pragma warning disable IDE1006
        public string value { get; set; }


        public DataType portDatatype { get; set; }
        public List<DataMapping> mappings { get; set; }



#pragma warning restore IDE1006
    }

}
