using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class DataMappingStep : AtomicStep
    {
#pragma warning disable IDE1006


        public List<DataMapping> mappings { get; set; }



#pragma warning restore IDE1006
    }

}
