namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class DataMapping : Identifiable, INameable
    {
#pragma warning disable IDE1006


        public DataType source { get; set; }
        public DataType target { get; set; }

        public string name { get; set; }


#pragma warning restore IDE1006
    }

}
