using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class DataType : Identifiable, INameable
    {
#pragma warning disable IDE1006


        public ComplexType belongsTo { get; set; }
        public List<DataMapping> mappings { get; set; }
        public List<DataPort> portMembers { get; set; }

        public string name { get; set; }



#pragma warning restore IDE1006
    }

}
