namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class EndDataPort : DataPort, EndPort
    {
#pragma warning disable IDE1006




        ///Implements for EndPort



#pragma warning restore IDE1006
    }

}
