namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class EndDataPortToStartDataPortMap
    {
#pragma warning disable IDE1006


        public EndDataPort key { get; set; }
        public StartDataPort value { get; set; }



#pragma warning restore IDE1006
    }

}
