namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class EscalationPort : EndControlPort
    {
#pragma warning disable IDE1006
        public long escalationTime { get; set; }





#pragma warning restore IDE1006
    }

}
