using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class GoalInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string invokeGoal { get; set; }
        public List<string> qualities { get; set; }
        public string location { get; set; }





#pragma warning restore IDE1006
    }

}
