
namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public enum HTTPverb
    {
        PUT = 0,
        GET = 1,
        POST = 2,
        DELETE = 3
    }

}
