namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class HumanTask : AtomicStep
    {
#pragma warning disable IDE1006
        public HumanTaskType humanTaskType { get; set; }
        public HumanTaskUseCase humanTaskUseCase { get; set; }





#pragma warning restore IDE1006
    }

}
