
namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public enum HumanTaskType
    {
        HINT = 0,
        WARNING = 1,
        INTERACTION = 2,
        ERROR = 3
    }

}
