
namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public enum HumanTaskUseCase
    {
        UNIVERSAL = 0,
        COFFEE = 1,
        HEATING = 2,
        ORDER = 3,
        PLANTS = 4,
        BELL = 5,
        HEALTH = 6
    }

}
