namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class Identifiable
    {
#pragma warning disable IDE1006
        public string id { get; set; }





#pragma warning restore IDE1006
    }

}
