namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class If : AtomicStep
    {
#pragma warning disable IDE1006


        public Condition ifCondition { get; set; }



#pragma warning restore IDE1006
    }

}
