namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public interface INameable
    {
#pragma warning disable IDE1006
        string name { get; set; }





#pragma warning restore IDE1006
    }

}
