namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class IntegerType : NumericType
    {
#pragma warning disable IDE1006
        public int min { get; set; }
        public int max { get; set; }





#pragma warning restore IDE1006
    }

}
