namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class LoadClassStep : AtomicStep
    {
#pragma warning disable IDE1006
        public string delegateClassName { get; set; }





#pragma warning restore IDE1006
    }

}
