using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class Loop : CompositeStep
    {
#pragma warning disable IDE1006


        public Condition loopCondition { get; set; }
        public List<EndDataPortToStartDataPortMap> portsCopyToStartsport { get; set; }



#pragma warning restore IDE1006
    }

}
