namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class OpenHabSemanticCommandInvoke : OpenHabSemanticInvoke
    {
#pragma warning disable IDE1006
        public string command { get; set; }





#pragma warning restore IDE1006
    }

}
