namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public abstract class OpenHabSemanticInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string query { get; set; }
        public string serverBaseAddress { get; set; }
        public bool withLatest { get; set; }





#pragma warning restore IDE1006
    }

}
