namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class OSGiInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string serviceClassName { get; set; }
        public string methodName { get; set; }
        public string parameterTypes { get; set; }
        public string bundleName { get; set; }





#pragma warning restore IDE1006
    }

}
