using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public abstract class Port : Identifiable, INameable
    {
#pragma warning disable IDE1006
        public bool optional { get; set; }
        public string description { get; set; }


        public List<Transition> outTransitions { get; set; }
        public ProcessStep processStep { get; set; }
        public Transition inTransitions { get; set; }

        public string name { get; set; }
#pragma warning restore IDE1006
    }

}
