using System.Collections.Generic;


namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class Process : CompositeStep
    {
#pragma warning disable IDE1006
        public string executionPeer { get; set; }
        public bool distributed { get; set; }
        public bool remoteExecuting { get; set; }


        public List<DataType> dataTypeDefinitions { get; set; }



#pragma warning restore IDE1006
    }

}
