namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public abstract class PublishMessage : AtomicStep
    {
#pragma warning disable IDE1006
        public string serverUri { get; set; }
        public string topic { get; set; }





#pragma warning restore IDE1006
    }

}
