namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class RESTInvoke : Invoke
    {
#pragma warning disable IDE1006
        public HTTPverb HTTPMethod { get; set; }
        public string ServerUri { get; set; }





#pragma warning restore IDE1006
    }

}
