namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class ROSInvoke : AtomicStep
    {
#pragma warning disable IDE1006
        public string serverUri { get; set; }
        public string serviceName { get; set; }





#pragma warning restore IDE1006
    }

}
