
namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public enum SemanticTargetType
    {
        ASK_QUERY = 0,
        SELECT_QUERY = 1,
        POST_COMMAND = 2
    }

}
