namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class SeMiWaInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string serviceName { get; set; }
        public string nodeId { get; set; }





#pragma warning restore IDE1006
    }

}
