namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
    public class SOAPInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string serverUri { get; set; }
        public string methodName { get; set; }
        public string wsdlUri { get; set; }
        public string configFile { get; set; }





#pragma warning restore IDE1006
    }

}
