namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class StartDataPort : DataPort, StartPort
    {
#pragma warning disable IDE1006




        ///Implements for StartPort



#pragma warning restore IDE1006
    }

}
