namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class Transition : Identifiable, INameable
    {

#pragma warning disable IDE1006 // Benennungsstile
        public Port sourcePort { get; set; }
#pragma warning restore IDE1006 // Benennungsstile
        public Port targetPort { get; set; }

        public string name { get; set; }


    }

}
