namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class TriggeredEvent : Event
    {
#pragma warning disable IDE1006
        public string EPLStatement { get; set; }





#pragma warning restore IDE1006
    }

}
