namespace HoloFlows.Processes.Sofia
{

    ///
    /// This Class was autogenerated with genmymodel.com
    ///
	public class XMLRPCInvoke : Invoke
    {
#pragma warning disable IDE1006
        public string serverUri { get; set; }
        public string methodName { get; set; }
        public string startParameterSequence { get; set; }
        public string endParameterSequence { get; set; }





#pragma warning restore IDE1006
    }

}
