/* 
 * PROtEUS REST API
 *
 * Accessing the PROtEUS runtime via REST
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;


namespace Processes.Proteus.Rest.Model
{
    /// <summary>
    /// IHumanTaskRequest
    /// </summary>
    [DataContract]
    public partial class IHumanTaskRequest : IEquatable<IHumanTaskRequest>
    {

        /// <summary>
        /// Gets or Sets HumanTaskUseCase
        /// </summary>
        [DataMember(Name = "humanTaskUseCase", EmitDefaultValue = false)]
        public HumanTaskUseCaseEnum? HumanTaskUseCase { get; set; }


        /// <summary>
        /// Gets or Sets HumanTaskType
        /// </summary>
        [DataMember(Name = "humanTaskType", EmitDefaultValue = false)]
        public HumanTaskTypeEnum? HumanTaskType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="IHumanTaskRequest" /> class.
        /// </summary>
        /// <param name="rootProcessId">rootProcessId.</param>
        /// <param name="dataMappingUtils">dataMappingUtils.</param>
        /// <param name="responded">responded.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="messageId">messageId.</param>
        /// <param name="name">name.</param>
        /// <param name="humanTaskUseCase">humanTaskUseCase.</param>
        /// <param name="humanTaskType">humanTaskType.</param>
        /// <param name="description">description.</param>
        /// <param name="endDataPorts">endDataPorts.</param>
        /// <param name="humanTaskInstanceId">humanTaskInstanceId.</param>
        /// <param name="startDataPorts">startDataPorts.</param>
        /// <param name="endControlPorts">endControlPorts.</param>
        public IHumanTaskRequest(string rootProcessId = default(string), List<IDataMappingUtil> dataMappingUtils = default(List<IDataMappingUtil>), bool? responded = default(bool?), long? timestamp = default(long?), string messageId = default(string), string name = default(string), HumanTaskUseCaseEnum? humanTaskUseCase = default(HumanTaskUseCaseEnum?), HumanTaskTypeEnum? humanTaskType = default(HumanTaskTypeEnum?), string description = default(string), Dictionary<string, IJSONDataPortInstance> endDataPorts = default(Dictionary<string, IJSONDataPortInstance>), string humanTaskInstanceId = default(string), Dictionary<string, IJSONDataPortInstance> startDataPorts = default(Dictionary<string, IJSONDataPortInstance>), Dictionary<string, IJSONPortInstance> endControlPorts = default(Dictionary<string, IJSONPortInstance>))
        {
            this.RootProcessId = rootProcessId;
            this.DataMappingUtils = dataMappingUtils;
            this.Responded = responded;
            this.Timestamp = timestamp;
            this.MessageId = messageId;
            this.Name = name;
            this.HumanTaskUseCase = humanTaskUseCase;
            this.HumanTaskType = humanTaskType;
            this.Description = description;
            this.EndDataPorts = endDataPorts;
            this.HumanTaskInstanceId = humanTaskInstanceId;
            this.StartDataPorts = startDataPorts;
            this.EndControlPorts = endControlPorts;
        }

        /// <summary>
        /// Gets or Sets RootProcessId
        /// </summary>
        [DataMember(Name = "rootProcessId", EmitDefaultValue = false)]
        public string RootProcessId { get; set; }

        /// <summary>
        /// Gets or Sets DataMappingUtils
        /// </summary>
        [DataMember(Name = "dataMappingUtils", EmitDefaultValue = false)]
        public List<IDataMappingUtil> DataMappingUtils { get; set; }

        /// <summary>
        /// Gets or Sets Responded
        /// </summary>
        [DataMember(Name = "responded", EmitDefaultValue = false)]
        public bool? Responded { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public long? Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets MessageId
        /// </summary>
        [DataMember(Name = "messageId", EmitDefaultValue = false)]
        public string MessageId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }



        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets EndDataPorts
        /// </summary>
        [DataMember(Name = "endDataPorts", EmitDefaultValue = false)]
        public Dictionary<string, IJSONDataPortInstance> EndDataPorts { get; set; }

        /// <summary>
        /// Gets or Sets HumanTaskInstanceId
        /// </summary>
        [DataMember(Name = "humanTaskInstanceId", EmitDefaultValue = false)]
        public string HumanTaskInstanceId { get; set; }

        /// <summary>
        /// Gets or Sets StartDataPorts
        /// </summary>
        [DataMember(Name = "startDataPorts", EmitDefaultValue = false)]
        public Dictionary<string, IJSONDataPortInstance> StartDataPorts { get; set; }

        /// <summary>
        /// Gets or Sets EndControlPorts
        /// </summary>
        [DataMember(Name = "endControlPorts", EmitDefaultValue = false)]
        public Dictionary<string, IJSONPortInstance> EndControlPorts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IHumanTaskRequest {\n");
            sb.Append("  RootProcessId: ").Append(RootProcessId).Append("\n");
            sb.Append("  DataMappingUtils: ").Append(DataMappingUtils).Append("\n");
            sb.Append("  Responded: ").Append(Responded).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  HumanTaskUseCase: ").Append(HumanTaskUseCase).Append("\n");
            sb.Append("  HumanTaskType: ").Append(HumanTaskType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EndDataPorts: ").Append(EndDataPorts).Append("\n");
            sb.Append("  HumanTaskInstanceId: ").Append(HumanTaskInstanceId).Append("\n");
            sb.Append("  StartDataPorts: ").Append(StartDataPorts).Append("\n");
            sb.Append("  EndControlPorts: ").Append(EndControlPorts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IHumanTaskRequest);
        }

        /// <summary>
        /// Returns true if IHumanTaskRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of IHumanTaskRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IHumanTaskRequest input)
        {
            if (input == null)
                return false;

            return
                (
                    this.RootProcessId == input.RootProcessId ||
                    (this.RootProcessId != null &&
                    this.RootProcessId.Equals(input.RootProcessId))
                ) &&
                (
                    this.DataMappingUtils == input.DataMappingUtils ||
                    this.DataMappingUtils != null &&
                    this.DataMappingUtils.SequenceEqual(input.DataMappingUtils)
                ) &&
                (
                    this.Responded == input.Responded ||
                    (this.Responded != null &&
                    this.Responded.Equals(input.Responded))
                ) &&
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) &&
                (
                    this.MessageId == input.MessageId ||
                    (this.MessageId != null &&
                    this.MessageId.Equals(input.MessageId))
                ) &&
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) &&
                (
                    this.HumanTaskUseCase == input.HumanTaskUseCase ||
                    (this.HumanTaskUseCase != null &&
                    this.HumanTaskUseCase.Equals(input.HumanTaskUseCase))
                ) &&
                (
                    this.HumanTaskType == input.HumanTaskType ||
                    (this.HumanTaskType != null &&
                    this.HumanTaskType.Equals(input.HumanTaskType))
                ) &&
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) &&
                (
                    this.EndDataPorts == input.EndDataPorts ||
                    this.EndDataPorts != null &&
                    this.EndDataPorts.SequenceEqual(input.EndDataPorts)
                ) &&
                (
                    this.HumanTaskInstanceId == input.HumanTaskInstanceId ||
                    (this.HumanTaskInstanceId != null &&
                    this.HumanTaskInstanceId.Equals(input.HumanTaskInstanceId))
                ) &&
                (
                    this.StartDataPorts == input.StartDataPorts ||
                    this.StartDataPorts != null &&
                    this.StartDataPorts.SequenceEqual(input.StartDataPorts)
                ) &&
                (
                    this.EndControlPorts == input.EndControlPorts ||
                    this.EndControlPorts != null &&
                    this.EndControlPorts.SequenceEqual(input.EndControlPorts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RootProcessId != null)
                    hashCode = hashCode * 59 + this.RootProcessId.GetHashCode();
                if (this.DataMappingUtils != null)
                    hashCode = hashCode * 59 + this.DataMappingUtils.GetHashCode();
                if (this.Responded != null)
                    hashCode = hashCode * 59 + this.Responded.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.MessageId != null)
                    hashCode = hashCode * 59 + this.MessageId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.HumanTaskUseCase != null)
                    hashCode = hashCode * 59 + this.HumanTaskUseCase.GetHashCode();
                if (this.HumanTaskType != null)
                    hashCode = hashCode * 59 + this.HumanTaskType.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.EndDataPorts != null)
                    hashCode = hashCode * 59 + this.EndDataPorts.GetHashCode();
                if (this.HumanTaskInstanceId != null)
                    hashCode = hashCode * 59 + this.HumanTaskInstanceId.GetHashCode();
                if (this.StartDataPorts != null)
                    hashCode = hashCode * 59 + this.StartDataPorts.GetHashCode();
                if (this.EndControlPorts != null)
                    hashCode = hashCode * 59 + this.EndControlPorts.GetHashCode();
                return hashCode;
            }
        }
    }

}
