/* 
 * PROtEUS REST API
 *
 * Accessing the PROtEUS runtime via REST
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Processes.Proteus.Rest.Model
{
    /// <summary>
    /// IJSONComplexType
    /// </summary>
    [DataContract]
    public partial class IJSONComplexType : IJSONType, IEquatable<IJSONComplexType>
    {

        protected override string CreateJavaClassInfo() { return "eu.vicci.process.model.util.serialization.jsontypes.JSONComplexType"; }

        /// <summary>
        /// Initializes a new instance of the <see cref="IJSONComplexType" /> class.
        /// </summary>
        /// <param name="SubTypes">SubTypes.</param>
        //public IJSONComplexType(List<IJSONType> SubTypes = default(List<IJSONType>), string Name = default(string), string Id = default(string), DataTypeTypeEnum? DataTypeType = default(DataTypeTypeEnum?), string TypeClass = default(string)) : base(Name, Id, DataTypeType, TypeClass)
        //{
        //    this.SubTypes = SubTypes;
        //}

        /// <summary>
        /// Gets or Sets SubTypes
        /// </summary>
        [DataMember(Name = "subTypes", EmitDefaultValue = false)]
        public List<IJSONType> SubTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IJSONComplexType {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  SubTypes: ").Append(SubTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IJSONComplexType);
        }

        /// <summary>
        /// Returns true if IJSONComplexType instances are equal
        /// </summary>
        /// <param name="input">Instance of IJSONComplexType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IJSONComplexType input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.SubTypes == input.SubTypes ||
                    this.SubTypes != null &&
                    this.SubTypes.SequenceEqual(input.SubTypes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.SubTypes != null)
                    hashCode = hashCode * 59 + this.SubTypes.GetHashCode();
                return hashCode;
            }
        }

    }

}
